all: 
	g++ -o mutex_lock_and_unlock mutex_lock_and_unlock.cpp  -lpthread
	g++ -o pthread_join pthread_join.cpp  -lpthread
	g++ -o stack_management Stack_Management.cpp -lpthread
	g++ -o sample_join sample_join.cpp -lpthread
clean:
	rm -rf mutex_lock_and_unlock
